schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.94.0"
    hash = "sha256-KWH2/qEc+CsddaX299o0COHNVHau1D8VvwBrZ0+dRyc="
  [mod."cloud.google.com/go/storage"]
    version = "v1.16.1"
    hash = "sha256-fWM30uP3VhTN1LM6406fWy+G/Pi16/d/14Zg5nB+Yo4="
  [mod."github.com/Azure/go-ntlmssp"]
    version = "v0.0.0-20200615164410-66371956d46c"
    hash = "sha256-yUABlT2ihU6GhLaXxfeZwAgJCtsiEe13giNNsLuRVTA="
  [mod."github.com/ChrisTrenkamp/goxpath"]
    version = "v0.0.0-20210404020558-97928f7e12b6"
    hash = "sha256-HBE7DokrpEzDqL4gvli9VacvrqAvmfLaMSyEu/h0qL8="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver"]
    version = "v1.5.0"
    hash = "sha256-3fEInOXFdzCiGdDZ1s9otEes7VXiL8Q1RVB3zXRPJsQ="
  [mod."github.com/Masterminds/sprig"]
    version = "v2.22.0+incompatible"
    hash = "sha256-7Q2DnQyL1Mu8S9PD86u62zZMrAkseiiDM3fATyTkvyU="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.3"
    hash = "sha256-d1lUB0kToOsPYfRmEh9SO+iVipgmsRs4xQkj1xlY9og="
  [mod."github.com/apparentlymart/go-textseg/v13"]
    version = "v13.0.0"
    hash = "sha256-Hn+zO0J/vnG5U6JvZfRyWm8vsqYdjh4RAreWnZLCQKQ="
  [mod."github.com/armon/go-metrics"]
    version = "v0.3.9"
    hash = "sha256-OiYJgbEQ6zP8EohO5X9QX5ua0r7Wd20NFY7Jpg//dmk="
  [mod."github.com/armon/go-radix"]
    version = "v1.0.0"
    hash = "sha256-A5SNdGtw8I6ngk9U3p+rKu6KB7inSngqmdnJl74EM9Q="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.40.34"
    hash = "sha256-ZvN7flHKevD+ehL+bZBnxFRq5oia5WWhYt1axIfkTDM="
  [mod."github.com/bgentry/go-netrc"]
    version = "v0.0.0-20140422174119-9fd32a8b3d3d"
    hash = "sha256-NDxQzO5C5M/aDz5/pjUHfZUh4VwIXovbb3irtxWCwjY="
  [mod."github.com/bgentry/speakeasy"]
    version = "v0.1.0"
    hash = "sha256-Gt1vj6CFovLnO6wX5u2O4UfecY9V2J9WGw1ez4HMrgk="
  [mod."github.com/cenkalti/backoff/v3"]
    version = "v3.2.2"
    hash = "sha256-Nam6FNUncrJN+ybAtRg34C8eg/ekPTfqUrkZqsMUBQY="
  [mod."github.com/dylanmei/iso8601"]
    version = "v0.1.0"
    hash = "sha256-oT/cGs5VRw+7GvAejnLhO5/aEwEDGlRilN6bxAlWpV8="
  [mod."github.com/fatih/camelcase"]
    version = "v1.0.0"
    hash = "sha256-VPzLJ5R6kWzrCwggUOhHlQ3XKW6nCOXxn+0kWZzh+Xw="
  [mod."github.com/fatih/color"]
    version = "v1.12.0"
    hash = "sha256-L0KGBvYZEFQ4vuWhIe/2E2rUERL4bsiFt+hHleAm2WQ="
  [mod."github.com/fatih/structtag"]
    version = "v1.2.0"
    hash = "sha256-Y2pjiEmMsxfUH8LONU2/f8k1BibOHeLKJmi4uZm/SSU="
  [mod."github.com/go-test/deep"]
    version = "v1.0.4"
    hash = "sha256-CjEiF+T7EMTZkgd47dNgwUJqg0rXnL2bwELHuZUG3uY="
  [mod."github.com/gofrs/flock"]
    version = "v0.8.1"
    hash = "sha256-pm3JJjYx+DjthmmdnIZQ4PvvtUVlpUTGiucIvmNI0dY="
  [mod."github.com/gofrs/uuid"]
    version = "v4.0.0+incompatible"
    hash = "sha256-LM2nBpmCAp32ihzuUx2xec3/6zLlvBWx8vJIxGX5YS8="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.6"
    hash = "sha256-OlzzRmcIdX45NA5h/C90NfJ/th0LB+tMHT6WzdQFK1M="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.1.0"
    hash = "sha256-6uZU1vBk5GsXyc/64HD1Np/4t/S4aJO5MXxMq7hnbaY="
  [mod."github.com/hashicorp/consul/api"]
    version = "v1.10.1"
    hash = "sha256-Jk6Fa5UXkRVhMPAqjA0tWCnGBMmdhMx9KFjhlUqAoJ0="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-cleanhttp"]
    version = "v0.5.2"
    hash = "sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ="
  [mod."github.com/hashicorp/go-getter/gcs/v2"]
    version = "v2.1.0"
    hash = "sha256-iecwUhXlvV1h2LYJwJxA3qdXZmkwTbCuf+L2ZbLB8lE="
  [mod."github.com/hashicorp/go-getter/s3/v2"]
    version = "v2.1.0"
    hash = "sha256-zAuMQNzZEeexq263SxMCrzOZpm4xaN103rHPFikutyI="
  [mod."github.com/hashicorp/go-getter/v2"]
    version = "v2.1.0"
    hash = "sha256-2/dPZngph3jazXksEAU3N4PDoNdnsmHSn7ga7ONdRW0="
  [mod."github.com/hashicorp/go-hclog"]
    version = "v0.16.2"
    hash = "sha256-yDgwZ5COW1o0a5TpiBa4KjZX5mg3B7Vs3AqoJFKhSYo="
  [mod."github.com/hashicorp/go-immutable-radix"]
    version = "v1.3.1"
    hash = "sha256-65+A2HiVfS/GV9G+6/TkXXjzXhI/V98e6RlJWjxy+mg="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/hashicorp/go-retryablehttp"]
    version = "v0.7.0"
    hash = "sha256-1KOm+BiuNUvJC+Y5qlwdcUyLBcaI43nXXtuT5fFRBt8="
  [mod."github.com/hashicorp/go-rootcerts"]
    version = "v1.0.2"
    hash = "sha256-prifkrFs+lawGTig3GwxddR0QM9E1+IpgZWCKoOnS5M="
  [mod."github.com/hashicorp/go-safetemp"]
    version = "v1.0.0"
    hash = "sha256-g5i9m7FSRInQzZ4iRpIsoUu685AY7fppUwjhuZCezT8="
  [mod."github.com/hashicorp/go-sockaddr"]
    version = "v1.0.2"
    hash = "sha256-bshn2I074/pnQ8gZU5RsfQRTrIvMC459bOfd/O/dHeo="
  [mod."github.com/hashicorp/go-version"]
    version = "v1.3.0"
    hash = "sha256-e+TurJ0ecxDDkQ1FZUL1G7NVWWIsMmMQDZgTiFuzz5c="
  [mod."github.com/hashicorp/golang-lru"]
    version = "v0.5.4"
    hash = "sha256-1skUMZX+iIf66J1TBVYGWO1OWwQcaoXut3mne331q+k="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.13.0"
    hash = "sha256-Y67be1wd7PI7Rmc4tX3klCE7fCokhZuvbXFmbfD1Htc="
  [mod."github.com/hashicorp/packer-plugin-sdk"]
    version = "v0.3.1"
    hash = "sha256-VAhaLwC9x5v53NZ0zZ5dRooAttbUgzUF5KQUtqOfTkw="
  [mod."github.com/hashicorp/serf"]
    version = "v0.9.5"
    hash = "sha256-4VJeZBD/rNqf3eij351y8v33cs0C413H4ri3jkzRXKg="
  [mod."github.com/hashicorp/vault/api"]
    version = "v1.1.1"
    hash = "sha256-7/kVU8dM/euEKlpu5aBMnib2Ynpd7slDy+joOxFhS+E="
  [mod."github.com/hashicorp/vault/sdk"]
    version = "v0.2.1"
    hash = "sha256-z45kjxVoxVndCCMRPH3wVF30uVSK3S1juSQIocLqQkk="
  [mod."github.com/hashicorp/yamux"]
    version = "v0.0.0-20210826001029-26ff87cf9493"
    hash = "sha256-PaJEsYnKOfBaBAc2jyKmuVpNEPsPOZTqkuoP+zt1VlI="
  [mod."github.com/huandu/xstrings"]
    version = "v1.3.2"
    hash = "sha256-ueAZrYRXMdRpeTKct3Yxa5YXkCZEoUHpNQs7wLLJil8="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.12"
    hash = "sha256-IPGunEznxlUilS22LUU4p/QTA7f5+Goowf1Utg9ARpc="
  [mod."github.com/jehiah/go-strftime"]
    version = "v0.0.0-20171201141054-1d33003b3869"
    hash = "sha256-+4WOjV+F2BXgKmdfYvuSkfQAKOZlFo8eZrnCT+xT3xQ="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/kr/fs"]
    version = "v0.1.0"
    hash = "sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c="
  [mod."github.com/masterzen/simplexml"]
    version = "v0.0.0-20190410153822-31eea3082786"
    hash = "sha256-R0uURq/a02WsoHfOEJvvHK7sZO7eXM1ArqGtF68U7gY="
  [mod."github.com/masterzen/winrm"]
    version = "v0.0.0-20210623064412-3b76017826b0"
    hash = "sha256-iRMuTH4GTGyKbHeTza+vPRulsspbIt8SaAniMX6QwoE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.8"
    hash = "sha256-TBXc2n5tRebabjt0HipS8wCdRml0kM0JjpppUbdx1XQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.13"
    hash = "sha256-8dof20YZW6ado90UG9kDrjCAnlWyRSOE3Jw4K3WEZyQ="
  [mod."github.com/mattn/go-tty"]
    version = "v0.0.4"
    hash = "sha256-ejvBdEXMYduy9rKEEb083tlYoYunAoXbIoYKC+Ce6lw="
  [mod."github.com/mitchellh/cli"]
    version = "v1.1.2"
    hash = "sha256-oGgYa4Djf8I/oYECpmxZzQg1uZUU2Xuqy/20mUUhZtk="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.0.0"
    hash = "sha256-Oeecmi8XpDvy7JUEmeIZ02B3c/tAS0A92QiBwEV60hY="
  [mod."github.com/mitchellh/go-fs"]
    version = "v0.0.0-20180402235330-b7b9ca407fff"
    hash = "sha256-krOdFdB/58iBhneBxtVSrTYAq0g+MyhuXs9eXnbOVb4="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-testing-interface"]
    version = "v1.14.1"
    hash = "sha256-TMGi38D13BEVN5cpeKDzKRIgLclm4ErOG+JEyqJrN/c="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v1.0.1"
    hash = "sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo="
  [mod."github.com/mitchellh/iochan"]
    version = "v1.0.0"
    hash = "sha256-b5Tp7cw/e8mL++IjsebbmKWXtb9Hrzu4Fc6M4tZKFhU="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.4.1"
    hash = "sha256-+xC5Th05FPFaWNMdAuX9YCwZpj0X1SD2t22a1VTkKNU="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.1"
    hash = "sha256-3WYlZ4a5czXVcAYpLp7u75XboNNVV4Z90WXzD+1QRl0="
  [mod."github.com/nu7hatch/gouuid"]
    version = "v0.0.0-20131221200532-179d4d0c4d8d"
    hash = "sha256-kjtBbQTeMAMtNAA/W35XuOtr7VCwBDW8EZUHXnp0Xsc="
  [mod."github.com/packer-community/winrmcp"]
    version = "v0.0.0-20180921211025-c76d91c1e7db"
    hash = "sha256-W82Zmamwko66mX5lKaD4fqQb/L2vpJWGmlQRzhSje0E="
  [mod."github.com/pierrec/lz4"]
    version = "v2.6.1+incompatible"
    hash = "sha256-5+4i5SN97wG71knAF9eUgEEG5k03HW4wPnAdPd6JSfE="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/sftp"]
    version = "v1.13.2"
    hash = "sha256-zJGpkJQCOqOEq3lMqwl6Pux88OB8JSOpIHiXz6jyIwg="
  [mod."github.com/posener/complete"]
    version = "v1.2.3"
    hash = "sha256-/17KFHD0SsGALg9iLXNIdvVFcotOO+H6bOOD5SY0MVs="
  [mod."github.com/rekby/mbr"]
    version = "v0.0.0-20151216101307-8c28b6465703"
    hash = "sha256-EiCLaLKutA+b7rb1HaefD9OV/bpyQHbtAQRCblo/tRk="
  [mod."github.com/ryanuber/go-glob"]
    version = "v1.0.0"
    hash = "sha256-YkMl1utwUhi3E0sHK23ISpAsPyj4+KeXyXKoFYGXGVY="
  [mod."github.com/stretchr/objx"]
    version = "v0.2.0"
    hash = "sha256-fx9mfz6FjbV2YtLQzk7Wzd+saejwoad2scLLC7Apvnw="
  [mod."github.com/ugorji/go/codec"]
    version = "v1.2.6"
    hash = "sha256-lieVJ9wVg8zvtA+V98TYM8b4P/Xuqp7ecoqoDPOws5M="
  [mod."github.com/ulikunitz/xz"]
    version = "v0.5.10"
    hash = "sha256-bogOwQNmQVS7W+C7wci7XEUeYm9TB7PnxnyBIXKYbm0="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.10.0"
    hash = "sha256-yjz6JxZKFiT9YxI6rnVpff1epkqbOLNYaigyEkYarfI="
  [mod."go.opencensus.io"]
    version = "v0.23.0"
    hash = "sha256-R3O9GyNtv6j0ic7s+2xkLLaLzbJEop0Otj1nJDFBjsg="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220517005047-85d78b3ac167"
    hash = "sha256-2LgRhdyB+l2dlYN/SKEEr1kp23UCThCOrUs9gba0pXI="
  [mod."golang.org/x/mod"]
    version = "v0.6.0-dev.0.20220106191415-9b9b3d81d5e3"
    hash = "sha256-S3jBYnuOhrLzhUb8Bqc/OE6va+4dF+4H9wvZpWwkLug="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20211112202133-69e39bad7dc2"
    hash = "sha256-X5AB9qPlau4aTEKaiNUPp4V4IyuX1JNFPnLwrzF+HKM="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20210819190943-2bc19b11175f"
    hash = "sha256-BpkR4sCAxqF/Ybas3FU5esyR3CB+k6KaAz3/8Hio6g0="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20211019181941-9d821ace8654"
    hash = "sha256-pQN+krYsvQtK6L3Bx2sMNyi/suaULVaHba2fYYhDdKg="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20210615171337-6886f2dfbf5b"
    hash = "sha256-ugNaJpGKXopRUQvIwjR5RqEuOGRmgxQjmWEqcdvhwRg="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."golang.org/x/tools"]
    version = "v0.1.10"
    hash = "sha256-dJr5LZ4nFQZFTvm5fFGRswCs71/qaTjbs72KeJJvAAw="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."google.golang.org/api"]
    version = "v0.56.0"
    hash = "sha256-ucGUMGP93NHmgDE2WOE17sdfn8/WidAi4qbFP2omzpY="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20210831024726-fe130286e0e2"
    hash = "sha256-1KmWgxnpU5Nep05YSV0D2OQtJ/2DRqm2HfMnHeAiYbk="
  [mod."google.golang.org/grpc"]
    version = "v1.40.0"
    hash = "sha256-8O5svL9J3wgPuwQrCl59ZpNlmasR6bP1PO1i3QC+5mw="
  [mod."google.golang.org/protobuf"]
    version = "v1.27.1"
    hash = "sha256-klLGFG4InPHIBDgisRph7H/02D5rBVx0ho9rZCRyLbk="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20201130134442-10cb98267c6c"
    hash = "sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs="
  [mod."gopkg.in/h2non/filetype.v1"]
    version = "v1.0.5"
    hash = "sha256-eCLu1Xi+Ft5iF0cbAvFuNLzW1gQJyHH2mDtaUjD3xe0="
  [mod."gopkg.in/square/go-jose.v2"]
    version = "v2.6.0"
    hash = "sha256-GRzbqF2tkyZ8/XEDkGNxF7TxBxd3z3umy/zD6jqGNqw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
